######################################################################
# Automatically generated by qmake (3.0) Thu May 11 14:58:40 2017
######################################################################

TEMPLATE = app
TARGET = indv_test
INCLUDEPATH += .
INCLUDEPATH += ../include/

# Input
HEADERS += can.hpp \
           disp.hpp \
           meter_ctrl.hpp \
           storage.hpp \
           ../include/lib.h \
           ../include/can.h \
           ../can/error.h \
           ../include/type.hpp

SOURCES += can.cpp disp.cpp lib.c meter_ctrl.cpp storage.cpp tester.cpp
