######################################################################
# Automatically generated by qmake (3.0) Thu May 11 14:58:40 2017
######################################################################

TEMPLATE = app
TARGET = indv_test
INCLUDEPATH += .
INCLUDEPATH += ../include/


QT += widgets

# Input
HEADERS += ../src/can.hpp \
           ../src/disp.hpp \
           ../src/meter_ctrl.hpp \
           ../src/storage.hpp \
           ../include/lib.h \
../include/can.h \
../include/can/error.h \
../include/type.hpp

SOURCES += ../src/can.cpp \
           ../src/disp.cpp \
           ../src/lib.c \
           ../src/meter_ctrl.cpp \
           ../src/storage.cpp \
           ../src/tester.cpp
            
