import json

#
# Json load can be useful to parse json-string generated by src/frame.c
#

def decode(frame):
    dec = json.loads(frame)

    print("spd=",dec['spd'])
    print("eng=",dec['eng'])
    print("fuel-consumpt=",dec['fuel_consumpt'])

if __name__ == "__main__":
    frame='{"spd":10,"eng":20,"fuel_consumpt":30}'
    decode(frame)
